<?php
include 'header.phtml';
include 'nav.phtml';
?>

    <!-- Page Content -->
    <div class="container">

        <!-- Portfolio Item Heading -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Contact Details</h1>
            </div>
        </div>
        <!-- /.row -->

        <!-- Portfolio Item Row -->
        <div class="row">

            
            <div class="col-md-12">
                
                <p>Email info@originchain.eu for more information about product authemtication services using distributed technology solutions.</p>
                
            </div>

        </div>
        <!-- /.row -->


<?php include 'footer.phtml'; ?> 