<?php
include 'header.phtml';
include 'nav.phtml';
?>

    <!-- Page Content -->
    <div class="container">
<div style="margin-top:48px;" class="notifications top-right"></div>
        <!-- Portfolio Item Heading -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Details of Verify by Bohemians FC & Origin Chain
                    <small><?php echo $signature; ?></small>
                </h1>

                <h3 class="page-header">Arranged in chronological order (Most recent first).
                </h1>
            </div>
        </div>
        <!-- /.row -->
<script>
    signature = '<?php echo $signature; ?>';

    function getItem(txid) {
        $.getJSON('/api/getitem/'+txid, function(data) {
            if (data.vout) {
                $.get('/api/getitem/'+txid+'/'+data.vout);
            }
        });
    }


    $.get( "/api/verify/"+ signature , function( data ) {

/*

    var container = document.getElementById('received_data');
    container.textContent = JSON.stringify(data);
    var pre = document.createElement("PRE");
    pre.textContent = JSON.stringify(data);
    document.getElementById('received_data').appendChild(pre);
*/


    Object.keys(data).forEach(function(k) {
        var items = [];
        items.push(
        '<table class="table table-striped table-hover"><thead><tr><th> Data </th><th> Value</th></tr></thead>');

        Object.keys(data[k]).forEach(function(key) {
            if (key=="transaction_id")
                items.push('<tr><td>' + key+ '</td><td>' + data[k][key]+ ' [<a href="javascript:getItem(\''+data[k][key]+'\');">item</a>]</td></tr>');
            else
                items.push('<tr><td>' + key+ '</td><td>' + data[k][key]+ '</td></tr>');
        });

        items.push('</table>');

        container = $("#received_data");

        $('<div/>', {
            'class': 'table',
            html: items.join('')
        }).appendTo(container);

    });

}); 
</script>   
        <!-- Portfolio Item Row -->
        <div class="row">
        
            <div class="col-md-12">
            <div id="received_data"></div>
            </div>

        </div>
        <!-- /.row -->


<?php include 'footer.phtml'; ?>        