<div id="description">
    <h3>Proof of Origin web-service</h3>
    <p>This tool harnesses the immense power of the Bitcoin blockchain to register each of our products and provide our customers with a guarantee of authenticy for their purchase.</p>
                
    <h3>How it works?</h3>
    <p>This web application provides a Proof-of-Origin service that benefits both suppliers and customers of branded retail goods. 
    <p>It does this by allowing retailers and producers to record sales items onto a blockchain distributed ledger and allowing customers to retrieve and verify the product details. 
    </p>
    
    <h3>How Product Registraion works?</h3>
    <ul>
        <li><b>Step 1:</b> Register item and upload to the blockchain on the Home page</li>
    </ul>
    
    <h3>How Verify works?</h3>
    <ul>
        <li><b>Step 1:</b> Scan the QR code on the tag with your mobile QR reader.</li>
        <li><b>Step 2:</b> Type the item code into the web-field</li>
        <li><b>Step 3:</b> The correct code will verify the product with the date &amp; time the item was created on the blockchain.</li>
    </ul>
</div>