<?php
include 'header.phtml';
include 'nav.phtml';
?>
<script src="js/publish.js" type="text/javascript"></script>
    <!-- Page Content -->
    <div class="container">
<div style="margin-top:48px;" class="notifications top-right"></div>
        <!-- Portfolio Item Heading -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Register product item<br>
                    <small>Input field data &amp; upload file.</small>
                </h1>
            </div>
        </div>
        <!-- /.row -->

        <!-- Portfolio Item Row -->
        <div class="row">
        
            <div class="col-md-8">
            <div id="form_container">
                <form id="upload_form" method="POST" enctype="multipart/form-data" action="api/v2/publish">
                  <div class="form-group">
                    <label for="name">Item: </label>
                    <input type="text" class="form-control" name="name" id="name" placeholder="Item" required>
                  </div>
                  <div class="form-group">
                    <label for="email">Email: </label>
                    <input type="email" class="form-control" name="email" id="email" placeholder="Your Email ID" required>
                  </div>
                  <div class="form-group">
                    <label for="message">Details: </label>
                    <textarea class="form-control" rows="3" maxlength="100" name="message" id="message" placeholder="(Optional) This item was created for BFC League Season 2017"></textarea>
                  </div>
                  
                  <div class="form-group">
                    <label for="poeFile">File to upload</label>
                    <div id="filedrag" style="display: none;" class="dropbox">
          Click here or drag and drop your document in the box.
          <br /> The file will be uploaded.
        </div>
        <div id="explain"></div>
        <div class="progress">
          <div class="progress-bar progress-bar-success progress-bar-striped"></div>
        </div>
        <fieldset>
            <input id='file' type="file" name="d" required/>
           
          </fieldset>
                    <!--<input type="file" id="poeFile">-->
                  </div>
                <input type="hidden" id="signature" name="signature" value="">
                  <button type="submit" id="btnSubmit" class="btn btn-primary">Submit</button>
                </form>
                </div>
                <br/>
                <br/>

                <div class="table-responsive">
                <h3>Recent inputs</h3>
                <table class="table table-striped table-hover" id="recently_published"></table>
                </div>
            
                <br/>
                <br/>

            </div>

            <div class="col-md-4">
            <div id="description_container">
                <?php include 'product_description.phtml'; ?> 
            </div>
            </div>

        </div>
        <!-- /.row -->


<?php include 'footer.phtml'; ?>